name: Publish Python Package

on:
  push:
    branches:
      - master  # Only run on pushes to the master branch

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code with submodules
      - name: Checkout code with submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive  # Ensure submodules are pulled

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9  # Adjust Python version as needed

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt  # If your project has dependencies

      # Step 4: Build and Publish to PyPI
      - name: Publish to PyPI
        run: |
          python -m pip install --upgrade build
          python -m build
          python -m pip install --upgrade twine
          python -m twine upload --non-interactive --repository pypi dist/*
        env:
          TWINE_USERNAME: "__token__"
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
